parameters:
  wordpress.driver.class: PaulGibbs\WordpressBehatExtension\Driver\Wpcli\WpcliDriver
  wordpress.element.cache.class: PaulGibbs\WordpressBehatExtension\Driver\Wpcli\Element\CacheElement
  wordpress.element.comment.class: PaulGibbs\WordpressBehatExtension\Driver\Wpcli\Element\CommentElement
  wordpress.element.content.class: PaulGibbs\WordpressBehatExtension\Driver\Wpcli\Element\ContentElement
  wordpress.element.database.class: PaulGibbs\WordpressBehatExtension\Driver\Wpcli\Element\DatabaseElement
  wordpress.element.plugin.class: PaulGibbs\WordpressBehatExtension\Driver\Wpcli\Element\PluginElement
  wordpress.element.term.class: PaulGibbs\WordpressBehatExtension\Driver\Wpcli\Element\TermElement
  wordpress.element.theme.class: PaulGibbs\WordpressBehatExtension\Driver\Wpcli\Element\ThemeElement
  wordpress.element.user.class: PaulGibbs\WordpressBehatExtension\Driver\Wpcli\Element\UserElement
  wordpress.element.widget.class: PaulGibbs\WordpressBehatExtension\Driver\Wpcli\Element\WidgetElement

services:
  wordpress.driver:
    class: "%wordpress.driver.class%"
    arguments:
      - "%wordpress.driver.alias%"
      - "%mink.base_url%"
      - "%wordpress.driver.binary%"
      - "%wordpress.path%"
    tags:
      - { name: wordpress.driver, alias: wpcli }

  wordpress.element.cache:
    class: "%wordpress.element.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: cache, driver: wpcli }

  wordpress.element.comment:
    class: "%wordpress.element.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: comment, driver: wpcli }

  wordpress.element.content:
    class: "%wordpress.element.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: content, driver: wpcli }

  wordpress.element.database:
    class: "%wordpress.element.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: database, driver: wpcli }

  wordpress.element.plugin:
    class: "%wordpress.element.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: plugin, driver: wpcli }

  wordpress.element.term:
    class: "%wordpress.element.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: term, driver: wpcli }

  wordpress.element.theme:
    class: "%wordpress.element.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: theme, driver: wpcli }

  wordpress.element.user:
    class: "%wordpress.element.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: user, driver: wpcli }

  wordpress.element.widget:
    class: "%wordpress.element.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: widget, driver: wpcli }
