parameters:
  wordpress.driver.class: PaulGibbs\WordpressBehatExtension\Driver\Wpphp\WpphpDriver
  wordpress.element.cache.class: PaulGibbs\WordpressBehatExtension\Driver\Wpphp\Element\CacheElement
  wordpress.element.comment.class: PaulGibbs\WordpressBehatExtension\Driver\Wpphp\Element\CommentElement
  wordpress.element.content.class: PaulGibbs\WordpressBehatExtension\Driver\Wpphp\Element\ContentElement
  wordpress.element.database.class: PaulGibbs\WordpressBehatExtension\Driver\Wpphp\Element\DatabaseElement
  wordpress.element.plugin.class: PaulGibbs\WordpressBehatExtension\Driver\Wpphp\Element\PluginElement
  wordpress.element.term.class: PaulGibbs\WordpressBehatExtension\Driver\Wpphp\Element\TermElement
  wordpress.element.theme.class: PaulGibbs\WordpressBehatExtension\Driver\Wpphp\Element\ThemeElement
  wordpress.element.user.class: PaulGibbs\WordpressBehatExtension\Driver\Wpphp\Element\UserElement
  wordpress.element.widget.class: PaulGibbs\WordpressBehatExtension\Driver\Wpphp\Element\WidgetElement

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  wordpress.driver:
    class: "%wordpress.driver.wpphp.class%"
    arguments:
      - "%wordpress.path%"
    tags:
      - { name: wordpress.driver, alias: wpphp }

  wordpress.element.cache:
    class: "%wordpress.element.cache.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: cache, driver: wpphp }

  wordpress.element.comment:
    class: "%wordpress.element.comment.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: , driver: wpphp }

  wordpress.element.content:
    class: "%wordpress.element.content.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: content, driver: wpphp }

  wordpress.element.database:
    class: "%wordpress.element.database.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: database, driver: wpphp }

  wordpress.element.plugin:
    class: "%wordpress.element.plugin.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: plugin, driver: wpphp }

  wordpress.element.term:
    class: "%wordpress.element.term.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: term, driver: wpphp }

  wordpress.element.theme:
    class: "%wordpress.element.theme.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: theme, driver: wpphp }

  wordpress.element.user:
    class: "%wordpress.element.user.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: user, driver: wpphp }

  wordpress.element.widget:
    class: "%wordpress.element.widget.class%"
    arguments:
      - "@wordpress.wordpress"
    tags:
      - { name: wordpress.element, alias: widget, driver: wpphp }
